# Generated by Django 4.2.1 on 2023-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nerf_id', models.IntegerField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
