# Generated by Django 4.2.1 on 2023-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerf',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
