# Generated by Django 4.2.1 on 2023-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_nerf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='low_glb',
            field=models.FileField(default='', upload_to='models/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='file',
            name='med_glb',
            field=models.FileField(default='', upload_to='models/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='nerf',
            name='slug',
            field=models.CharField(max_length=400),
        ),
    ]
