# Generated by Django 4.2.1 on 2023-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_file_low_glb_file_med_glb_alter_file_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='low_glb',
            field=models.FileField(upload_to='models/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='med_glb',
            field=models.FileField(upload_to='models/%Y/%m/%d/'),
        ),
    ]
