# Generated by Django 4.2.1 on 2023-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_file_low_glb_alter_file_med_glb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user_id', models.IntegerField()),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RenameField(
            model_name='nerf',
            old_name='created',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='nerf',
            old_name='user_id',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='nerf',
            name='title',
        ),
    ]
