# Generated by Django 4.2.1 on 2023-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_video_delete_file_rename_created_nerf_called_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerf',
            name='called_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
