# Generated by Django 4.2.1 on 2023-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_nerf_called_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('low_glb', models.FileField(upload_to='models/%Y/%m/%d/')),
                ('med_glb', models.FileField(upload_to='models/%Y/%m/%d/')),
            ],
        ),
    ]
