# Generated by Django 4.2.1 on 2023-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_exporttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttest',
            name='nerf_id',
            field=models.IntegerField(default=0),
        ),
    ]
