# Generated by Django 4.2.1 on 2023-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_exporttest_nerf_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nerf_id', models.IntegerField()),
                ('thumb', models.CharField(max_length=500)),
                ('low_model', models.CharField(max_length=500)),
            ],
        ),
    ]
