# Generated by Django 4.2.1 on 2023-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_exporturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerf',
            name='title',
            field=models.TextField(default='New Capture'),
        ),
    ]
