# Generated by Django 4.2.1 on 2023-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_nerf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerf',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
