# Generated by Django 4.2.1 on 2023-07-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_nerf_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_id',
        ),
    ]
