# Generated by Django 4.2.3 on 2023-07-10 06:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_nerf_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[home.models.validate_file_extension]),
        ),
    ]
