# Generated by Django 4.2.1 on 2023-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_exporturl_high_model_exporturl_med_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='nerf',
            name='apikey',
            field=models.CharField(default='apikey', max_length=500),
        ),
    ]
