# Generated by Django 4.2.1 on 2023-07-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_nerf_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerf',
            name='apikey',
            field=models.CharField(default='', max_length=500),
        ),
    ]
